name: triton-florence2-development-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python ==3.12.5
  - numpy ==1.26.4
  - protobuf
  - pytorch ==2.5.1
  - pytorch-cuda ==12.4
  - torchvision ==0.20.1
  - einops ==0.8.0
  - timm ==1.0.11
  - transformers ==4.46.2
  - pillow ==11.0.0
  - requests
  - ipython
  - ruff
  - pip
   #- pip:
     # pip deps
