name: florence2_model
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - python ==3.10.12
    - numpy ==1.26.4 # Finding that many models break if using numpy=2.0
    - pip
    - protobuf
    - pytorch ==2.5.1
    - torchvision ==0.20.1
    - pytorch-cuda ==12.4
    - einops ==0.8.0
    - timm ==1.0.11
    - transformers ==4.46.2
    # - sentencepiece ==0.2.0
    - pillow ==11.0.0
    - conda-pack
