name: "florence2_process"
backend: "python"
max_batch_size: 36
default_model_filename: "florence2_process.py"

input [
    {
        name: "INPUT_IMAGE"
        data_type: TYPE_STRING
        dims: [1]
    },
    {
        name: "TASK_PROMPT"
        data_type: TYPE_STRING
        dims: [1]
    },
    {
        name: "TEXT_PROMPT"
        data_type: TYPE_STRING
        dims: [1]
        optional: true
    }
]
output [
    {
        name: "INPUT_IDS"
        data_type: TYPE_INT64
        dims: [-1]
    },
    {
        name: "ATTENTION_MASK"
        data_type: TYPE_INT64
        dims: [-1]
    },
    {
        name: "PIXEL_VALUES"
        data_type: TYPE_FP32
        dims: [3, 768, 768]
    },
    {
        name: "IMAGE_SIZE"
        data_type: TYPE_INT64
        dims: [2]
    }
]

parameters: [
    {
        key: "EXECUTION_ENV_PATH"
        value: {string_value: "$$TRITON_MODEL_DIRECTORY/florence2_process.tar.gz"}
    },
    {
        key: "model_subfolder"
        value: {
            string_value: "models--mrhendrey--Florence-2-large-ft-safetensors/snapshots/9b1cdec1c01073aa0b0a4bdcd5ce0989da38bf95/"
        }
    }
]

instance_group [
    {
        kind: KIND_CPU
        count: 4
    }
]

version_policy: {latest: {num_versions: 1}}
dynamic_batching: {max_queue_delay_microseconds: 100}
