name: florence2_process
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python ==3.10.12
    - numpy ==1.26.4 # Finding that many models break if using numpy=2.0
    - pip
    - protobuf
    - pytorch ==2.5.1
    - cpuonly ==2.0
    - transformers ==4.46.2
    # - sentencepiece ==0.2.0
    - pillow ==11.0.0
    - conda-pack
